// Sprint weekends: China (R02), Miami (R06), Canada (R07), GB (R11), Netherlands (R14), Singapore (R18)
export const RACES = [
  {
    id: "r01", round: 1,  name: "Australian GP",
    circuit: "Albert Park Circuit",       country: "Australia",    flag: "🇦🇺",
    date: "Mar 14–16, 2026", city: "Melbourne",
    sprint: false, laps: 58, length: 5.278,
    lapRecord: { time: "1:20.235", holder: "Leclerc", year: 2022 },
  },
  {
    id: "r02", round: 2,  name: "Chinese GP",
    circuit: "Shanghai International Circuit", country: "China",   flag: "🇨🇳",
    date: "Mar 20–22, 2026", city: "Shanghai",
    sprint: true,  laps: 56, length: 5.451,
    lapRecord: { time: "1:32.238", holder: "Hamilton", year: 2004 },
  },
  {
    id: "r03", round: 3,  name: "Japanese GP",
    circuit: "Suzuka International Racing Course", country: "Japan", flag: "🇯🇵",
    date: "Apr 3–5, 2026", city: "Suzuka",
    sprint: false, laps: 53, length: 5.807,
    lapRecord: { time: "1:30.983", holder: "Hamilton", year: 2019 },
  },
  {
    id: "r04", round: 4,  name: "Bahrain GP",
    circuit: "Bahrain International Circuit",  country: "Bahrain",  flag: "🇧🇭",
    date: "Apr 17–19, 2026", city: "Sakhir",
    sprint: false, laps: 57, length: 5.412,
    lapRecord: { time: "1:31.447", holder: "De la Rosa", year: 2005 },
  },
  {
    id: "r05", round: 5,  name: "Saudi Arabian GP",
    circuit: "Jeddah Corniche Circuit",         country: "Saudi Arabia", flag: "🇸🇦",
    date: "Apr 24–26, 2026", city: "Jeddah",
    sprint: false, laps: 50, length: 6.174,
    lapRecord: { time: "1:30.734", holder: "Leclerc", year: 2022 },
  },
  {
    id: "r06", round: 6,  name: "Miami GP",
    circuit: "Miami International Autodrome",   country: "USA",      flag: "🇺🇸",
    date: "May 1–3, 2026", city: "Miami",
    sprint: true,  laps: 57, length: 5.412,
    lapRecord: { time: "1:29.708", holder: "Verstappen", year: 2023 },
  },
  {
    id: "r07", round: 7,  name: "Canadian GP",
    circuit: "Circuit Gilles Villeneuve",       country: "Canada",   flag: "🇨🇦",
    date: "May 22–24, 2026", city: "Montréal",
    sprint: true,  laps: 70, length: 4.361,
    lapRecord: { time: "1:13.078", holder: "Bottas", year: 2019 },
  },
  {
    id: "r08", round: 8,  name: "Monaco GP",
    circuit: "Circuit de Monaco",              country: "Monaco",   flag: "🇲🇨",
    date: "Jun 5–7, 2026", city: "Monte Carlo",
    sprint: false, laps: 78, length: 3.337,
    lapRecord: { time: "1:12.909", holder: "Leclerc", year: 2021 },
  },
  {
    id: "r09", round: 9,  name: "Spanish GP",
    circuit: "Circuit de Barcelona-Catalunya",  country: "Spain",    flag: "🇪🇸",
    date: "Jun 12–14, 2026", city: "Barcelona",
    sprint: false, laps: 66, length: 4.657,
    lapRecord: { time: "1:18.149", holder: "Verstappen", year: 2021 },
  },
  {
    id: "r10", round: 10, name: "Austrian GP",
    circuit: "Red Bull Ring",                  country: "Austria",  flag: "🇦🇹",
    date: "Jun 26–28, 2026", city: "Spielberg",
    sprint: false, laps: 71, length: 4.318,
    lapRecord: { time: "1:05.619", holder: "Bottas", year: 2020 },
  },
  {
    id: "r11", round: 11, name: "British GP",
    circuit: "Silverstone Circuit",            country: "United Kingdom", flag: "🇬🇧",
    date: "Jul 3–5, 2026", city: "Silverstone",
    sprint: true,  laps: 52, length: 5.891,
    lapRecord: { time: "1:27.097", holder: "Hamilton", year: 2020 },
  },
  {
    id: "r12", round: 12, name: "Belgian GP",
    circuit: "Circuit de Spa-Francorchamps",   country: "Belgium",  flag: "🇧🇪",
    date: "Jul 17–19, 2026", city: "Stavelot",
    sprint: false, laps: 44, length: 7.004,
    lapRecord: { time: "1:46.286", holder: "Bottas", year: 2018 },
  },
  {
    id: "r13", round: 13, name: "Hungarian GP",
    circuit: "Hungaroring",                    country: "Hungary",  flag: "🇭🇺",
    date: "Jul 24–26, 2026", city: "Budapest",
    sprint: false, laps: 70, length: 4.381,
    lapRecord: { time: "1:16.627", holder: "Hamilton", year: 2020 },
  },
  {
    id: "r14", round: 14, name: "Dutch GP",
    circuit: "Circuit Zandvoort",              country: "Netherlands", flag: "🇳🇱",
    date: "Aug 21–23, 2026", city: "Zandvoort",
    sprint: true,  laps: 72, length: 4.259,
    lapRecord: { time: "1:11.097", holder: "Verstappen", year: 2021 },
  },
  {
    id: "r15", round: 15, name: "Italian GP",
    circuit: "Autodromo Nazionale Monza",      country: "Italy",    flag: "🇮🇹",
    date: "Sep 4–6, 2026", city: "Monza",
    lapRecord: { time: "1:21.046", holder: "Barrichello", year: 2004 },
    sprint: false, laps: 53, length: 5.793,
  },
  {
    id: "r16", round: 16, name: "Madrid GP",
    circuit: "Madrid Street Circuit",          country: "Spain",    flag: "🇪🇸",
    date: "Sep 11–13, 2026", city: "Madrid",
    sprint: false, laps: 65, length: 5.476,
    lapRecord: { time: "TBD", holder: "—", year: null },
  },
  {
    id: "r17", round: 17, name: "Azerbaijan GP",
    circuit: "Baku City Circuit",              country: "Azerbaijan", flag: "🇦🇿",
    date: "Sep 24–26, 2026", city: "Baku",
    sprint: false, laps: 51, length: 6.003,
    lapRecord: { time: "1:43.009", holder: "Leclerc", year: 2019 },
  },
  {
    id: "r18", round: 18, name: "Singapore GP",
    circuit: "Marina Bay Street Circuit",      country: "Singapore", flag: "🇸🇬",
    date: "Oct 9–11, 2026", city: "Singapore",
    sprint: true,  laps: 62, length: 4.940,
    lapRecord: { time: "1:35.867", holder: "Leclerc", year: 2023 },
  },
  {
    id: "r19", round: 19, name: "United States GP",
    circuit: "Circuit of the Americas",        country: "USA",      flag: "🇺🇸",
    date: "Oct 23–25, 2026", city: "Austin",
    sprint: false, laps: 56, length: 5.513,
    lapRecord: { time: "1:36.169", holder: "Hamilton", year: 2019 },
  },
  {
    id: "r20", round: 20, name: "Mexico City GP",
    circuit: "Autódromo Hermanos Rodríguez",   country: "Mexico",   flag: "🇲🇽",
    date: "Oct 30–Nov 1, 2026", city: "Mexico City",
    sprint: false, laps: 71, length: 4.304,
    lapRecord: { time: "1:17.774", holder: "Hamilton", year: 2021 },
  },
  {
    id: "r21", round: 21, name: "São Paulo GP",
    circuit: "Autódromo José Carlos Pace",     country: "Brazil",   flag: "🇧🇷",
    date: "Nov 6–8, 2026", city: "São Paulo",
    sprint: false, laps: 71, length: 4.309,
    lapRecord: { time: "1:10.540", holder: "Barrichello", year: 2004 },
  },
  {
    id: "r22", round: 22, name: "Las Vegas GP",
    circuit: "Las Vegas Street Circuit",       country: "USA",      flag: "🇺🇸",
    date: "Nov 19–21, 2026", city: "Las Vegas",
    sprint: false, laps: 50, length: 6.201,
    lapRecord: { time: "1:35.490", holder: "Leclerc", year: 2023 },
  },
  {
    id: "r23", round: 23, name: "Qatar GP",
    circuit: "Lusail International Circuit",   country: "Qatar",    flag: "🇶🇦",
    date: "Nov 27–29, 2026", city: "Lusail",
    sprint: false, laps: 57, length: 5.380,
    lapRecord: { time: "1:24.319", holder: "Hamilton", year: 2021 },
  },
  {
    id: "r24", round: 24, name: "Abu Dhabi GP",
    circuit: "Yas Marina Circuit",             country: "UAE",      flag: "🇦🇪",
    date: "Dec 4–6, 2026", city: "Abu Dhabi",
    sprint: false, laps: 58, length: 5.281,
    lapRecord: { time: "1:26.103", holder: "Hamilton", year: 2021 },
  },
];
